- templates/Overall-Cover.html.tmpl
- templates/Overall-TIR-Cover.html.tmpl
> add tag / environment to overall TIR / DTR

- templates/Overall-TIR-Cover.html.tmpl
Add exported commits and tags (as aligned with QA)
> Release/v add generated tags to overal TIR

- templates/CSD-1.html.tmpl
- templates/CSD-3.html.tmpl
- templates/CSD-4.html.tmpl
- templates/CSD-5.html.tmpl
- templates/DTR.html.tmpl
- templates/TIP.html.tmpl
PR to to correct some minor typos found in a couple of templates.
> Correct minor typos

- templates/CFTP-1.html.tmpl
- templates/CFTP-3.html.tmpl
- templates/CFTP-4.html.tmpl
- templates/CFTP-5.html.tmpl
> Fix chapter numbers in C-FTP documents

- README.md
- css/styles.css
- templates/CFTP-1.html.tmpl
- templates/CFTP-3.html.tmpl
- templates/CFTP-4.html.tmpl
- templates/CFTP-5.html.tmpl
- templates/CFTR-1.html.tmpl
- templates/CFTR-3.html.tmpl
- templates/CFTR-4.html.tmpl
- templates/CFTR-5.html.tmpl
- templates/CSD-1.html.tmpl
- templates/CSD-3.html.tmpl
- templates/CSD-4.html.tmpl
- templates/CSD-5.html.tmpl
- templates/DTP.html.tmpl
- templates/DTR.html.tmpl
- templates/IVP.html.tmpl
- templates/IVR.html.tmpl
- templates/Overall-TIR-Cover.html.tmpl
- templates/RA.html.tmpl
- templates/SSDS-1.html.tmpl
- templates/SSDS-3.html.tmpl
- templates/SSDS-4.html.tmpl
- templates/SSDS-5.html.tmpl
- templates/TCP.html.tmpl
- templates/TCR.html.tmpl
- templates/TIP.html.tmpl
- templates/TIR-infra.html.tmpl
- templates/TIR.html.tmpl
- templates/TRC.html.tmpl
This branch merges previous changes to the `release/v1.1` branch back into `master`.
@jorge-romero @stitakis @hrcornejo @jafarre-viewnext @louis-sanchez in the future, I suggest that you make changes directly into the integration branch `master` instead of a release branch. This way, you only need to create a single PR into `master`, which can only be changed through a pull requests (protected branch). Then, you can `git merge` or `git cherry-pick` changes into a release branch. Thoughts?
> Changes from release/v1.1

- README.md
- css/styles.css
- templates/CFTP-1.html.tmpl
- templates/CFTP-3.html.tmpl
- templates/CFTP-4.html.tmpl
- templates/CFTP-5.html.tmpl
- templates/CFTR-1.html.tmpl
- templates/CFTR-3.html.tmpl
- templates/CFTR-4.html.tmpl
- templates/CFTR-5.html.tmpl
- templates/CSD-1.html.tmpl
- templates/CSD-3.html.tmpl
- templates/CSD-4.html.tmpl
- templates/CSD-5.html.tmpl
- templates/DTP.html.tmpl
- templates/DTR.html.tmpl
- templates/IVP.html.tmpl
- templates/IVR.html.tmpl
- templates/Overall-TIR-Cover.html.tmpl
- templates/RA.html.tmpl
- templates/SSDS-1.html.tmpl
- templates/SSDS-3.html.tmpl
- templates/SSDS-4.html.tmpl
- templates/SSDS-5.html.tmpl
- templates/TCP.html.tmpl
- templates/TCR.html.tmpl
- templates/TIP.html.tmpl
- templates/TIR-infra.html.tmpl
- templates/TIR.html.tmpl
- templates/TRC.html.tmpl
Follow-up to #24 after additional changes to `release/v1.1`.
> Merge from release/v1.1 into master

- templates/CFTP-1.html.tmpl
- templates/CFTP-3.html.tmpl
- templates/CFTP-4.html.tmpl
- templates/CFTP-5.html.tmpl
- templates/CFTR-1.html.tmpl
- templates/CFTR-3.html.tmpl
- templates/CFTR-4.html.tmpl
- templates/CFTR-5.html.tmpl
- templates/CSD-1.html.tmpl
- templates/CSD-3.html.tmpl
- templates/CSD-4.html.tmpl
- templates/CSD-5.html.tmpl
- templates/DTP.html.tmpl
- templates/DTR.html.tmpl
- templates/IVP.html.tmpl
- templates/IVR.html.tmpl
- templates/RA.html.tmpl
- templates/SSDS-1.html.tmpl
- templates/SSDS-3.html.tmpl
- templates/SSDS-4.html.tmpl
- templates/SSDS-5.html.tmpl
- templates/TCP.html.tmpl
- templates/TCR.html.tmpl
- templates/TIP.html.tmpl
- templates/TIR.html.tmpl
- templates/TRC.html.tmpl
Initially used to show heading number and title for documentation chapters
> Add optional details to the document-history entries

- .github/workflows/changelog-enforcer.yml
- .gitignore
- CHANGELOG.md
also added .gitignore and CHANGELOG.md
> added changelog-enforcer as github action

- CHANGELOG.md
- css/styles.css
- templates/CFTP-1.html.tmpl
- templates/CFTP-3.html.tmpl
- templates/CFTP-4.html.tmpl
- templates/CFTP-5.html.tmpl
- templates/CFTR-1.html.tmpl
- templates/CFTR-3.html.tmpl
- templates/CFTR-4.html.tmpl
- templates/CFTR-5.html.tmpl
- templates/CSD-1.html.tmpl
- templates/CSD-3.html.tmpl
- templates/CSD-4.html.tmpl
- templates/CSD-5.html.tmpl
- templates/DTP.html.tmpl
- templates/DTR.html.tmpl
- templates/RA.html.tmpl
- templates/SSDS-1.html.tmpl
- templates/SSDS-3.html.tmpl
- templates/SSDS-4.html.tmpl
- templates/SSDS-5.html.tmpl
- templates/TCP.html.tmpl
- templates/TCR.html.tmpl
- templates/TIP.html.tmpl
- templates/TIR-infra.html.tmpl
- templates/TIR.html.tmpl
- templates/TRC.html.tmpl
Remove the border from the wrapping table to improve Leva document quality
> Remove border from wrapper table

- CHANGELOG.md
- css/styles.css
- templates/CFTP-1.html.tmpl
- templates/CFTP-3.html.tmpl
- templates/CFTP-4.html.tmpl
- templates/CFTP-5.html.tmpl
- templates/CFTR-1.html.tmpl
- templates/CFTR-3.html.tmpl
- templates/CFTR-4.html.tmpl
- templates/CFTR-5.html.tmpl
- templates/CSD-1.html.tmpl
- templates/CSD-3.html.tmpl
- templates/CSD-4.html.tmpl
- templates/CSD-5.html.tmpl
- templates/DTP.html.tmpl
- templates/DTR.html.tmpl
- templates/RA.html.tmpl
- templates/SSDS-1.html.tmpl
- templates/SSDS-3.html.tmpl
- templates/SSDS-4.html.tmpl
- templates/SSDS-5.html.tmpl
- templates/TCP.html.tmpl
- templates/TCR.html.tmpl
- templates/TIP.html.tmpl
- templates/TIR-infra.html.tmpl
- templates/TIR.html.tmpl
- templates/TRC.html.tmpl
Remove the border from the wrapping table to improve Leva document quality
> Remove border from wrapper table (v1.1)

- CHANGELOG.md
- templates/CFTP-3.html.tmpl
- templates/CFTP-4.html.tmpl
- templates/CFTP-5.html.tmpl
> cftp changes based on veeva crm feedback - master

- CHANGELOG.md
- templates/CFTP-3.html.tmpl
- templates/CFTP-4.html.tmpl
- templates/CFTP-5.html.tmpl
> cftp changes for veeva crm - edp 1.2

- CHANGELOG.md
- templates/CFTP-3.html.tmpl
- templates/CFTP-4.html.tmpl
- templates/CFTP-5.html
- templates/CFTP-5.html.tmpl
> CFTP for GAMP3/4/5 improvements

- CHANGELOG.md
- templates/CFTP-3.html.tmpl
- templates/CFTP-4.html.tmpl
- templates/CFTP-5.html.tmpl
Adds missing chapter numbers for chapters 8.2.1 and 8.2.2
> Add missing chapter numbers

- CHANGELOG.md
- templates/CSD-3.html.tmpl
- templates/CSD-4.html.tmpl
- templates/SSDS-1.html.tmpl
- templates/SSDS-3.html.tmpl
- templates/SSDS-4.html.tmpl
- templates/SSDS-5.html.tmpl
- templates/TIR.html.tmpl
Update release/v1.2 branch for new release
> Update release/v1.2 branch for new release

- CHANGELOG.md
- templates/RA.html.tmpl
- templates/SSDS-1.html.tmpl
- templates/SSDS-3.html.tmpl
- templates/SSDS-4.html.tmpl
- templates/SSDS-5.html.tmpl
> Fix ssds gamp and RA chapter 5

- CHANGELOG.md
- templates/IVR.html.tmpl
> Fix HTML is not interpreted in IVR document

- CHANGELOG.md
- css/styles.css
Cherry pick into release branch of https://github.com/opendevstack/ods-document-generation-templates/pull/114
> Prepare release branch 1.2.5

- CHANGELOG.md
- templates/TRC.html.tmpl
Fix #128, make section's 4 table cells wrappable
> fix: TRC Make section 4 table wrappable

- CHANGELOG.md
- templates/CSD-1.html.tmpl
- templates/CSD-3.html.tmpl
- templates/CSD-4.html.tmpl
- templates/CSD-5.html.tmpl
> Center alignment for first column

- CHANGELOG.md
- templates/IVP.html.tmpl
- templates/IVR.html.tmpl
- templates/Overall-TIR-Cover.html.tmpl
- templates/RA.html.tmpl
- templates/SSDS-1.html.tmpl
- templates/SSDS-3.html.tmpl
- templates/SSDS-4.html.tmpl
- templates/SSDS-5.html.tmpl
- templates/TIP.html.tmpl
> Prepare release 1.2.8
